# build.ps1 -- assembles rom.asm and emits rom_image.h for main.c to #include.
#
# Pipeline: sdaslh5801 -> sdld -> makebin (mirrors tools/vscode-lh5801-asm's
# assembleAsm() in the pc1500emu repo), then a direct parse of the linked
# .ihx to build rom_image.h -- NOT a parse of the makebin .bin. makebin
# fills gaps between data records (i.e. .blkb regions, like the demoted
# pages 1-3 and the unused tail of pages 4/5) with 0xFF, which is exactly
# right for rom.bin (loadable into pc1500emu/real hardware as blank/erased
# ROM) but wrong for rom_image.h: main.c's InitBuffer() copies this into a
# RAM buffer it explicitly zeroes first, so gaps must be left alone (0x00),
# not overwritten with 0xFF. Parsing the .ihx directly and emitting one
# memcpy per contiguous record sidesteps the mismatch instead of fighting
# makebin's fill convention.
#
# Toolchain paths match .vscode/settings.json in the pc1500emu repo
# (sdaslh5801/sdld/makebin all built natively under sdcc-pc1500/sdcc/bin_vc).
# Adjust these if your checkout lives elsewhere.

$ErrorActionPreference = "Stop"

$sdas    = "C:\Users\paulc\sdcc-pc1500\sdcc\bin_vc\sdaslh5801.exe"
$sdld    = "C:\Users\paulc\sdcc-pc1500\sdcc\bin_vc\sdld.exe"
$makebin = "C:\Users\paulc\sdcc-pc1500\sdcc\bin_vc\makebin.exe"

foreach ($tool in @($sdas, $sdld, $makebin)) {
    if (-not (Test-Path $tool)) { throw "Required tool not found: $tool" }
}

Push-Location $PSScriptRoot
try {
    Remove-Item -ErrorAction SilentlyContinue rom.rel, rom.lst, rom.ihx, rom.bin, rom_8800.bin, rom.lnk, rom.sym, rom.map, rom.rst

    & $sdas -l -o rom.rel rom.asm
    if ($LASTEXITCODE -ne 0) { throw "sdaslh5801 failed (exit $LASTEXITCODE)" }

    Set-Content -NoNewline -Path rom.lnk -Value "-muwx`n-i rom`nrom.rel`n`n-e`n"
    & $sdld -nf rom
    if ($LASTEXITCODE -ne 0) { throw "sdld failed (exit $LASTEXITCODE)" }
    if (-not (Test-Path rom.ihx)) { throw "sdld produced no rom.ihx" }

    # rom.bin: flat image for loadrommodule/real hardware, blank regions as 0xFF.
    # Anchored at 0x8000 (the board's fixed WINDOW_BASE, see rom_defs.inc) --
    # byte 0 of this file is address 0x8000, not ROM_BASE (0x8800), since
    # main.c's LoadRomImage() copies it into rom[32][256], which spans the
    # whole 8K window starting at 0x8000.
    & $makebin -p -s 0x10000 -o 0x8000 rom.ihx rom.bin
    if ($LASTEXITCODE -ne 0) { throw "makebin failed (exit $LASTEXITCODE)" }

    # rom_8800.bin: same content, anchored at ROM_BASE (0x8800) instead --
    # i.e. byte 0 IS the sentinel, no leading 0x800 bytes of blank filler.
    # For pc1500emu's `loadexpansionmodule`, which wants just the ROM bytes
    # separately from the data window (which it allocates and manages on
    # its own) -- loading rom.bin there at base 0x8000 would otherwise let
    # its own blank-filled data-window bytes permanently shadow the real
    # writable window underneath (confirmed live this session: every write
    # into 0x8000-0x8FFF silently no-op'd until this was caught).
    & $makebin -p -s 0x10000 -o 0x8800 rom.ihx rom_8800.bin
    if ($LASTEXITCODE -ne 0) { throw "makebin failed (exit $LASTEXITCODE)" }

    # --- Parse rom.ihx directly for rom_image.h -----------------------
    $romBase = 0x8000
    $chunks = New-Object System.Collections.Generic.List[object]
    foreach ($line in Get-Content rom.ihx) {
        if (-not $line.StartsWith(":")) { continue }
        $byteCount = [Convert]::ToInt32($line.Substring(1, 2), 16)
        $addr      = [Convert]::ToInt32($line.Substring(3, 4), 16)
        $recType   = [Convert]::ToInt32($line.Substring(7, 2), 16)
        if ($recType -ne 0) { continue }  # only data records
        $bytes = New-Object System.Collections.Generic.List[byte]
        for ($i = 0; $i -lt $byteCount; $i++) {
            $bytes.Add([Convert]::ToInt32($line.Substring(9 + $i * 2, 2), 16))
        }
        $chunks.Add([PSCustomObject]@{ Offset = $addr - $romBase; Bytes = $bytes })
    }
    if ($chunks.Count -eq 0) { throw "rom.ihx had no data records -- nothing to embed" }

    # Merge chunks that are byte-adjacent (consecutive sdld records for the
    # same run of code/data) so rom_image.h needs fewer, larger memcpys.
    $merged = New-Object System.Collections.Generic.List[object]
    foreach ($c in $chunks) {
        if ($merged.Count -gt 0) {
            $last = $merged[$merged.Count - 1]
            if ($last.Offset + $last.Bytes.Count -eq $c.Offset) {
                $last.Bytes.AddRange($c.Bytes)
                continue
            }
        }
        $merged.Add([PSCustomObject]@{ Offset = $c.Offset; Bytes = [System.Collections.Generic.List[byte]]$c.Bytes })
    }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("/* rom_image.h -- auto-generated by rom/build.ps1 from rom.asm. */")
    [void]$sb.AppendLine("/* Do not edit by hand -- edit rom.asm and re-run build.ps1.    */")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("typedef struct { uint16 offset; uint16 length; } RomImageChunk;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("static const uint8 kRomImageData[] = {")
    $allBytes = New-Object System.Collections.Generic.List[byte]
    foreach ($m in $merged) { $allBytes.AddRange($m.Bytes) }
    for ($i = 0; $i -lt $allBytes.Count; $i += 16) {
        $lineBytes = $allBytes.GetRange($i, [Math]::Min(16, $allBytes.Count - $i))
        $hex = ($lineBytes | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
        [void]$sb.AppendLine("    $hex,")
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("static const RomImageChunk kRomImageChunks[] = {")
    foreach ($m in $merged) {
        [void]$sb.AppendLine(("    {{ 0x{0:X4}, {1} }}," -f $m.Offset, $m.Bytes.Count))
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("static void LoadRomImage(uint8 rom[32][256])")
    [void]$sb.AppendLine("{")
    [void]$sb.AppendLine("    const uint8* src = kRomImageData;")
    [void]$sb.AppendLine("    uint8* base = &rom[0][0];")
    [void]$sb.AppendLine("    for (uint8 i = 0; i < sizeof(kRomImageChunks) / sizeof(kRomImageChunks[0]); i++)")
    [void]$sb.AppendLine("    {")
    [void]$sb.AppendLine("        memcpy(base + kRomImageChunks[i].offset, src, kRomImageChunks[i].length);")
    [void]$sb.AppendLine("        src += kRomImageChunks[i].length;")
    [void]$sb.AppendLine("    }")
    [void]$sb.AppendLine("}")

    Set-Content -NoNewline -Path rom_image.h -Value $sb.ToString()
    Write-Host "Wrote rom_image.h: $($allBytes.Count) real bytes across $($merged.Count) chunk(s), rom.bin: $((Get-Item rom.bin).Length) bytes, rom_8800.bin: $((Get-Item rom_8800.bin).Length) bytes"
}
finally {
    Pop-Location
}
