"""gen_tz_table.py -- writes tz_table.c, MCONF TZ's IANA zone names, the
POSIX TZ rule each one follows and any changes already scheduled before
that rule takes over (2026-10-08, time_zone.h).

The rule is the footer of the zone's TZif file (RFC 8536 sec.3.3), which
describes the zone only from its last listed transition on. Most zones'
last transition is long past, but some list future ones -- Morocco's
Ramadan changes to 2087, BC and Alberta going permanent in 2026 -- so each
zone also gets its transitions from CUTOFF on, with the offset in effect at
CUTOFF first.

Usage:
    python -I tools/gen_tz_table.py <zoneinfo dir> [tz_table.c]

<zoneinfo dir> is a TZif tree with a `zones` list beside it, e.g. the
`tzdata` PyPI package's (pip install --target <dir> tzdata, then
<dir>/tzdata/zoneinfo). The output is committed, so building the firmware
doesn't need Python.
"""
import datetime
import glob
import os
import struct
import sys

CUTOFF = int(datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc).timestamp())


def read_tzif(path):
    """(transitions [(utc, offset)], footer) from a version 2+ TZif file's
    64-bit part, or None."""
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"TZif" or data[4:5] < b"2":
        return None

    def header(at):
        return struct.unpack(">4sc15x6l", data[at:at + 44])

    _, _, isut, isstd, leap, timecnt, typecnt, charcnt = header(0)
    at = 44 + timecnt * 5 + typecnt * 6 + charcnt + leap * 8 + isstd + isut  # past the 32-bit part
    _, _, isut, isstd, leap, timecnt, typecnt, charcnt = header(at)
    at += 44
    times = struct.unpack(">%dq" % timecnt, data[at:at + 8 * timecnt])
    at += 8 * timecnt
    indices = data[at:at + timecnt]
    at += timecnt
    types = [struct.unpack(">lBB", data[at + 6 * i:at + 6 * i + 6])[0] for i in range(typecnt)]
    at += 6 * typecnt + charcnt + leap * 12 + isstd + isut
    rule = data[at:].strip(b"\n").decode("ascii")
    return [(t, types[i]) for t, i in zip(times, indices)], rule or None


def scheduled(transitions):
    """The transitions after CUTOFF, after the offset in effect at CUTOFF;
    [] when the footer already covers everything from CUTOFF on."""
    if not transitions or transitions[-1][0] <= CUTOFF:
        return []
    before = [o for t, o in transitions if t <= CUTOFF]
    out = [(CUTOFF, before[-1])] if before else []
    return out + [(t, o) for t, o in transitions if t > CUTOFF]


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    root = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "tz_table.c")
    found = glob.glob(os.path.join(os.path.dirname(os.path.normpath(root)), "..", "tzdata-*.dist-info"))
    version = os.path.basename(found[0])[7:-10] if found else "(version unknown)"
    zones_file = os.path.join(os.path.dirname(os.path.normpath(root)), "zones")
    if os.path.exists(zones_file):
        with open(zones_file) as f:
            names = [line.strip() for line in f if line.strip()]
    else:
        names = []
        for dirpath, _, files in os.walk(root):
            for name in files:
                names.append(os.path.relpath(os.path.join(dirpath, name), root).replace(os.sep, "/"))
    entries = {}
    for name in names:
        path = os.path.join(root, *name.split("/"))
        if not os.path.isfile(path):
            continue
        tzif = read_tzif(path)
        if tzif is None or tzif[1] is None:
            print(f"skipped {name}: no POSIX footer", file=sys.stderr)
            continue
        entries[name] = (tzif[1], tuple(scheduled(tzif[0])))
    # time_zone.c binary-searches in its own order: upper case, '_' as ' '
    key = lambda n: n.upper().replace("_", " ")
    ordered = sorted(entries, key=key)
    rules = sorted(set(r for r, _ in entries.values()))
    rule_index = {r: i for i, r in enumerate(rules)}
    shifts, shift_at = [], {}
    for name in ordered:
        sched = entries[name][1]
        if sched and sched not in shift_at:
            shift_at[sched] = len(shifts)
            shifts.extend(sched)
    lines = [
        "/* tz_table.c -- GENERATED by tools/gen_tz_table.py from tzdata; don't edit.",
        f" * tzdata {version}: each IANA zone, the POSIX TZ rule it follows, and the",
        " * changes scheduled from 2026 until that rule takes over (time_zone.h). */",
        '#include "time_zone.h"',
        "",
        "static const char *const kRules[] = {",
    ]
    lines += [f'    "{r}",' for r in rules]
    lines += ["};", "", "const tz_shift_t kTzShifts[] = {"]
    lines += [f"    {{{t}, {o}}}," for t, o in shifts] or ["    {0, 0},"]
    lines += ["};", "", "const tz_entry_t kTzTable[] = {"]
    for name in ordered:
        rule, sched = entries[name]
        first = shift_at[sched] if sched else 0
        lines.append(f'    {{"{name}", {rule_index[rule]}, {first}, {len(sched)}}},')
    lines += [
        "};",
        "",
        "const unsigned kTzTableCount = sizeof kTzTable / sizeof kTzTable[0];",
        "",
        "const char *tz_table_rule(unsigned index) { return kRules[kTzTable[index].rule]; }",
        "",
    ]
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{len(ordered)} zones, {len(rules)} rules, {len(shifts)} scheduled changes -> {out}")


if __name__ == "__main__":
    main()
