/* monitor.c
 *
 * Ported from Design01_NonDMA_8K_PV_Swap.cydsn/main.c -- see that file
 * and this repo's plan history for the full background. Two halves,
 * now running on separate cores (changed 2026-09-17 -- see below):
 *
 *   1. monitor_run()'s bus loop (core0): on the GreenPAK's read-trigger
 *      (CS && Read && OE), drive the data pins from buffer[page][laddress];
 *      on the write-trigger (CS && Write), latch data into the buffer, or
 *      hand off to core1 if the write landed on the instruction address.
 *      Direct SIO register reads throughout (sio_hw->gpio_in/gpio_out/
 *      gpio_oe), not per-pin gpio_get()/gpio_put() calls -- those go
 *      through more machinery than a ~2us budget can afford. This loop
 *      never blocks, not even for a command's duration.
 *   2. monitor_command_worker()'s DoCommand() (core1): the same ~30-case
 *      EXP_COMMAND_* switch, translated case-by-case from SEGGER emFile's
 *      FS_* API to FatFs's f_* API. Blocks core1 for a command's whole
 *      duration; core0 is unaffected and keeps servicing the bus.
 *
 * RAM RESIDENCY -- deliberately NOT applied here. DoCommand() and this
 * file's loop don't need __not_in_flash_func the way qmi_cs1_spi.c/
 * qmi_cs1_sd.c do -- those needed it to keep their own internal per-byte
 * transfer loops from deadlocking against their own open QMI transaction
 * (see their own top comments), a QMI-specific hazard this design never
 * had to think about at all.
 *
 * WHY TWO CORES (changed 2026-09-17, was single-core): the original
 * single-core design had core0 call DoCommand() directly from inside the
 * bus loop, blocking the whole loop for the command's duration -- on the
 * theory (matching the PSoC5 original, which really does work this way)
 * that any bus read landing on the status byte *while DoCommand() runs*
 * would see whatever was last physically latched on the data pins, and
 * the ROM-side poll loop would just keep spinning until a real answer
 * came back once DoCommand() returned. That theory doesn't hold on this
 * board: this design releases the data bus to Hi-Z with a pull-DOWN
 * between transactions (see InitGpio()'s own comment), so "whatever was
 * last latched" during a long DoCommand() call is actually a floating
 * bus reading as 0x00 -- which is EXP_STATUS_READY's own value (see
 * pc_exp.h), completely indistinguishable from a real "done" answer.
 * Confirmed live 2026-09-17: SDLS's own SD_LIST_POLL busy-wait (rom.asm)
 * would see this false READY almost immediately, read directory data
 * DoCommand() hadn't written yet, and crash with a different garbage-
 * triggered BASIC error (ERROR 40/120/122, never the same one twice)
 * every time. A same-core fix (core0 explicitly driving EXP_STATUS_BUSY
 * and holding it for the whole call) was tried first and worked, but
 * still left core0 unable to service anything else for a command's whole
 * duration -- moving DoCommand() to core1 removes that limitation
 * entirely rather than just papering over its one known symptom.
 */
#include "monitor.h"

#include <string.h>

#include "hardware/structs/sio.h"
#include "hardware/gpio.h"
#include "hardware/sync.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "pico/stdlib.h"
#include "pico/time.h"
#include "pico/cyw43_arch.h"
#include "pico/multicore.h"

#include "ff.h"
#include "board_pins.h"
#include "pc_exp.h"
#include "read_serve.pio.h"

/* rom_image.h is generated by ../Design01_NonDMA_8K_PV_Swap.cydsn/rom/
 * build.ps1 from rom.asm -- the LH5801-side ROM content is identical
 * regardless of which MCU serves it, so this includes that same
 * generated file directly (CMakeLists.txt adds its directory to the
 * include path) rather than hand-copying it, so it can never drift from
 * the PSoC5 side. It uses PSoC's uint8/uint16 typedefs (normally pulled
 * in via project.h there); #define'd here just for this include so the
 * generated file itself doesn't need touching. */
#define uint8 uint8_t
#define uint16 uint16_t
#include "rom_image.h"
#undef uint8
#undef uint16

/* ---- Shared 8K data window: pages 0-7 (2K live data window) plus
 * pages 8-31 (6K ROM region, only actually driven through this buffer
 * while Control_Mode_Control-equivalent GreenPAK state selects
 * ROM_FROM_MCU during the boot copy -- see PC_EXP.h's own top comment).
 *
 * 8192-byte aligned (2026-09-18) -- the PIO-driven read path
 * (read_serve.pio's addr_capture program, see SetupReadServePio() below)
 * builds a complete absolute RAM address by shifting a fixed prefix (this
 * buffer's own high address bits) ahead of the live 13-bit address bus
 * value. That only produces the right address if this buffer's base
 * address has all ADDR_PIN_COUNT low bits clear -- i.e. is aligned to its
 * own size (8192 = 2^13). GCC/Clang's `aligned` attribute on a static
 * array guarantees the linker places it on that boundary. */
static uint8_t buffer[32][256] __attribute__((aligned(8192)));

/* Command watchdog, checked by core0 (never core1 -- core1 may be deep
 * inside a blocked call and can't watch its own clock). `buffer`'s status
 * byte is the single source of truth for "a command is in flight" (==
 * EXP_STATUS_BUSY); g_command_start_us is only meaningful while that's
 * true, refreshed every time core0 dispatches a new command. This is a
 * backstop, not the primary fix -- greenpak_i2c.c's own I2C_SCL_TIMEOUT_US
 * bound (2026-09-17) already converts the one known unbounded hang into a
 * fast, clean failure. This catches anything that's merely slow (or any
 * future bug in the same class) by forcing the status to ERROR once a
 * command has been running too long, so the LH5801's own busy-poll loop
 * (which has no timeout of its own) always gets an answer.
 *
 * Widened from the original 2s (2026-09-17) -- that value was chosen for
 * SDLS specifically and directly broke the DOSTUFF isolation test it was
 * never meant to cover: DOSTUFF 5/8 were firing this watchdog at 2s,
 * forcing ERROR while core1 kept legitimately sleeping in the background,
 * then racing core1's own late real WriteStatus() against this one for
 * whichever value the LH5801's next poll happened to sample -- exactly
 * the inconsistent BAD STATUS/OK results seen live. 30s comfortably
 * covers DOSTUFF's own test range; this still needs to become per-command
 * eventually (SDLS itself only needs ~2s worst case -- see
 * diskio_sd_bridge.c's SD_INIT_TIMEOUT_US -- so 30s is far looser than
 * ideal for real commands, just deliberately out of DOSTUFF's way for now).
 * NOTE: this does not free up core1 if it's genuinely wedged -- it only
 * lets the bus/LH5801 side recover. A wedged core1 still won't process
 * any later command until reset, unless/until the low-level blocking
 * calls are changed to cooperatively check an abort flag themselves. */
#define COMMAND_TIMEOUT_US 30000000u
static uint32_t g_command_start_us = 0;

/* Ported from Design01_NonDMA_8K_PV_Swap.cydsn/main.c's InitBuffer/
 * LoadRomImage: zeroes the shared window, then memcpys each sparse
 * chunk of kRomImageData into place at its kRomImageChunks offset.
 * Must run before monitor_run() starts servicing bus reads (main.c's
 * job, before launching core1) -- otherwise the ROM region reads back
 * as whatever main.c's caller catches. */
void monitor_init_buffer(void) {
    memset(buffer, 0, sizeof(buffer));
    const uint8_t *src = kRomImageData;
    uint8_t *base = &buffer[0][0];
    for (size_t i = 0; i < sizeof(kRomImageChunks) / sizeof(kRomImageChunks[0]); i++) {
        memcpy(base + kRomImageChunks[i].offset, src, kRomImageChunks[i].length);
        src += kRomImageChunks[i].length;
    }
}

static FIL currentFile;
static bool currentFileOpen = false;
static uint8_t currentFileStatus = EXP_SD_FILE_STATUS_CLOSED;
static uint32_t fileEnd = 0;
static char currentFileName[64];

static FIL channelFile[EXP_MAX_SD_CHANNELS];
static bool channelOpen[EXP_MAX_SD_CHANNELS];
static char channelName[EXP_MAX_SD_CHANNELS][EXP_PATH_ARG_LEN + 1];
static uint32_t channelReadPos[EXP_MAX_SD_CHANNELS];

/* ============================================================
 * Buffer/string helpers -- filesystem-API-agnostic, ported verbatim
 * from main.c. (DataFromBuffer is not ported: it's dead code in the
 * original too, referenced only from a commented-out call.)
 * ============================================================ */

static void LongToBuffer(uint8_t buf[16][256], int8_t page, int8_t start, uint32_t value) {
    buf[page][start] = (uint8_t)((value >> 24) & 0xFF);
    buf[page][start + 1] = (uint8_t)((value >> 16) & 0xFF);
    buf[page][start + 2] = (uint8_t)((value >> 8) & 0xFF);
    buf[page][start + 3] = (uint8_t)(value & 0xFF);
}

static void StringFromBuffer(uint8_t buf[16][256], uint8_t page, uint8_t start, uint16_t length,
                              char result[]) {
    const uint8_t *b = &buf[page][start];
    for (uint16_t i = 0; i < length; i++) result[i] = (char)*b++;
    result[length] = 0;
}

static void FormatSizeText(uint32_t value, uint8_t result[], uint8_t width) {
    uint8_t i;
    for (i = 0; i < width; i++) result[i] = ' ';
    i = width;
    do {
        i--;
        result[i] = (uint8_t)('0' + (value % 10));
        value /= 10;
    } while (value != 0 && i > 0);
}

static uint8_t WriteDecimal(uint32_t value, uint8_t result[]) {
    uint8_t buf[10];
    uint8_t n = 0;
    uint8_t i;
    if (value == 0) {
        result[0] = '0';
        return 1;
    }
    while (value != 0) {
        buf[n++] = (uint8_t)('0' + (value % 10));
        value /= 10;
    }
    for (i = 0; i < n; i++) result[i] = buf[n - 1 - i];
    return n;
}

static void FormatSummaryLine(uint16_t count, uint32_t totalBytes, uint32_t freeBytes,
                               uint8_t result[], uint8_t width) {
    char temp[48];
    uint8_t pos = 0;
    uint8_t i;
    pos = (uint8_t)(pos + WriteDecimal(count, (uint8_t *)(temp + pos)));
    temp[pos++] = ' ';
    temp[pos++] = 'F';
    temp[pos++] = 'I';
    temp[pos++] = 'L';
    temp[pos++] = 'E';
    temp[pos++] = 'S';
    temp[pos++] = ' ';
    pos = (uint8_t)(pos + WriteDecimal(totalBytes, (uint8_t *)(temp + pos)));
    temp[pos++] = 'B';
    temp[pos++] = ' ';
    pos = (uint8_t)(pos + WriteDecimal(freeBytes, (uint8_t *)(temp + pos)));
    temp[pos++] = 'F';
    for (i = 0; i < width; i++) result[i] = (i < pos) ? (uint8_t)temp[i] : ' ';
}

static void NormalizeSdPathFromFs(const char *raw, char *out, uint8_t outSize) {
    const char *colon = strchr(raw, ':');
    const char *src = colon ? colon + 1 : raw;
    uint8_t n = 0;
    out[n++] = '/';
    for (; *src != 0 && n < outSize - 1; src++) {
        char c = (*src == '\\') ? '/' : *src;
        if (n == 1 && c == '/') continue;
        out[n++] = c;
    }
    out[n] = 0;
}

static void ConvertSdPathToFsSeparators(char *path) {
    for (; *path != 0; path++)
        if (*path == '/') *path = '\\';
}

static void ConvertPlusToTilde(char *name) {
    for (; *name != 0; name++)
        if (*name == '+') *name = '~';
}

static void ConvertTildeToPlus(char *name) {
    for (; *name != 0; name++)
        if (*name == '~') *name = '+';
}

static void PrepareFsName(const char *raw, char *out, uint8_t outSize) {
    strncpy(out, raw, outSize - 1);
    out[outSize - 1] = 0;
    ConvertPlusToTilde(out);
    ConvertSdPathToFsSeparators(out);
}

static const char *GetBasename(const char *path) {
    const char *base = path;
    for (const char *p = path; *p != 0; p++)
        if (*p == '/' || *p == '\\') base = p + 1;
    return base;
}

/* FatFs equivalent of FS_GetFileAttributes(path) & FS_ATTR_DIRECTORY --
 * f_stat() failing (file doesn't exist) is treated as "not a directory",
 * same as the original's implicit behavior when the emFile call fails. */
static bool IsDirectory(const char *path) {
    FILINFO fno;
    if (f_stat(path, &fno) != FR_OK) return false;
    return (fno.fattrib & AM_DIR) != 0;
}

static void ResolveCopyOrMoveDestination(const char *srcBasename, const char *destArg, char *out,
                                          uint8_t outSize) {
    char converted[EXP_PATH_ARG_LEN + 1];
    PrepareFsName(destArg, converted, sizeof(converted));
    if (IsDirectory(converted)) {
        uint8_t n = 0;
        for (; converted[n] != 0 && n < outSize - 1; n++) out[n] = converted[n];
        if (n > 0 && out[n - 1] != '\\' && n < outSize - 1) out[n++] = '\\';
        uint8_t i = 0;
        while (srcBasename[i] != 0 && n < outSize - 1) out[n++] = srcBasename[i++];
        out[n] = 0;
    } else {
        strncpy(out, converted, outSize - 1);
        out[outSize - 1] = 0;
    }
}

/* FS_CopyFile has no FatFs equivalent -- manual read/write-loop copy. */
static bool CopyFileFatFs(const char *srcPath, const char *destPath) {
    FIL src, dst;
    if (f_open(&src, srcPath, FA_READ) != FR_OK) return false;
    if (f_open(&dst, destPath, FA_CREATE_ALWAYS | FA_WRITE) != FR_OK) {
        f_close(&src);
        return false;
    }
    uint8_t chunk[512];
    UINT br, bw;
    FRESULT fr = FR_OK;
    for (;;) {
        fr = f_read(&src, chunk, sizeof(chunk), &br);
        if (fr != FR_OK || br == 0) break;
        fr = f_write(&dst, chunk, br, &bw);
        if (fr != FR_OK || bw != br) {
            fr = FR_DISK_ERR;
            break;
        }
        if (br < sizeof(chunk)) break; /* short read == end of file */
    }
    f_close(&src);
    f_close(&dst);
    return fr == FR_OK;
}

/* FS_FSeek(file, offset, FS_SEEK_END) equivalent -- FatFs's f_lseek only
 * takes an absolute offset, so "seek to end" means seek to f_size(). */
static void SeekToEnd(FIL *fp) { f_lseek(fp, f_size(fp)); }

/* FS_GetVolumeFreeSpace/FS_GetVolumeSize equivalent, via the standard
 * FatFs idiom (f_getfree + fs->csize + sector size), not emFile's
 * single-call equivalents. */
static void GetVolumeSpace(uint32_t *totalBytes, uint32_t *freeBytes) {
    DWORD freeClusters = 0;
    FATFS *fs = NULL;
    if (f_getfree("", &freeClusters, &fs) != FR_OK || fs == NULL) {
        *totalBytes = 0;
        *freeBytes = 0;
        return;
    }
    *freeBytes = (uint32_t)freeClusters * fs->csize * FF_MAX_SS;
    *totalBytes = (uint32_t)(fs->n_fatent - 2) * fs->csize * FF_MAX_SS;
}

static void WriteStatus(uint8_t buf[16][256], uint8_t status) {
    /* Barrier before publishing the status byte -- WriteStatus(SUCCESS)
     * (or ERROR/etc.) is always the LAST thing a DoCommand() case does,
     * after populating real data elsewhere in `buffer` (e.g.
     * EXP_COMMAND_LIST_SD_DIR writing the directory count/entries/summary
     * before its final WriteStatus() call). `buffer` is a plain,
     * non-volatile array shared between this core (core1) and core0's
     * bus loop, which serves LH5801 reads directly from it -- without
     * this, neither the compiler nor the hardware is obligated to make
     * those earlier writes visible to core0 before this one lands, so
     * the LH5801 could correctly see a non-BUSY status yet still read
     * stale/torn directory data underneath it. Plausible root cause
     * (2026-09-17, pre-dating and independent of the HLT polling
     * experiment) for ERROR 122/garbage-on-screen after SDLS -- a
     * genuine cross-core visibility gap, not the busy-wait mechanism
     * itself. __dmb() ensures the hardware orders prior stores from this
     * core ahead of this one; the compiler memory clobber ensures GCC
     * doesn't reorder them past each other in the first place. */
    __compiler_memory_barrier();
    __dmb();
    buf[EXP_INSTRUCTION_PAGE][EXP_INSTRUCTION_ADDRESS] = status;
}

/* ============================================================
 * DoCommand -- ~30-case switch, ported from main.c's DoCommand(),
 * FS_* -> f_*. Case-by-case commentary kept where the FatFs mapping
 * isn't 1:1; see this file's own header and RP2350/README.md for the
 * general notes (FS_RmDir/f_unlink-on-a-directory, FS_ChDir/FF_FS_RPATH,
 * FS_CopyFile/CopyFileFatFs, volume free/total via f_getfree).
 * ============================================================ */
static void DoCommand(uint8_t req, uint8_t buf[16][256]) {
    WriteStatus(buf, EXP_STATUS_BUSY);
    switch (req) {
        case EXP_COMMAND_ROM_FROM_SRAM: {
            /* GreenPAK mode-select, over the I2C link -- board_pins.h's
             * PIN_GREENPAK1_SDA/SCL. greenpak_virtual_io.h now provides
             * the register-level protocol (greenpak_virtual_input_set),
             * and this almost certainly maps directly to setting GP1's
             * SRAM/ROM Remap virtual input high (see GreenPakTester's
             * selftest.h/GP1_VI_SRAM_ROM_REMAP and the GreenPAK design
             * doc's "ROM/SRAM toggles" section) -- not yet wired up here
             * because this board's GP1/GP2 I2C slave addresses aren't
             * assigned yet (pending the NVM-programming feature that
             * sets each chip's control code away from default so they
             * don't collide on the shared bus). */
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_ROM_FROM_MCU: {
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_GET_SD_FREE_SPACE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint32_t total, free_;
            GetVolumeSpace(&total, &free_);
            LongToBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS, free_);
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_GET_SD_VOLUME_SIZE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint32_t total, free_;
            GetVolumeSpace(&total, &free_);
            LongToBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS, total);
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_GET_SD_FILE_SIZE: {
            if (!currentFileOpen) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint32_t fileSize = (uint32_t)f_size(&currentFile);
            LongToBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS, fileSize);
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_READ_SD_VOLUME_LABEL: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t volumeNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                      buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (volumeNameLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char volumeName[EXP_PATH_ARG_LEN + 1];
            if (volumeNameLen > EXP_PATH_ARG_LEN) volumeNameLen = EXP_PATH_ARG_LEN;
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2,
                              volumeNameLen, volumeName);
            char label[34];
            if (f_getlabel(volumeName, label, NULL) != FR_OK) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint8_t labelLen = (uint8_t)strlen(label);
            buf[EXP_SCRATCH_PAGE][0] = labelLen;
            for (uint8_t i = 0; i < labelLen; i++) buf[EXP_SCRATCH_PAGE][i + 1] = label[i];
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_GET_SD_FILE_NAME: {
            if (!currentFileOpen) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t nameLen = (uint8_t)strlen(currentFileName);
            buf[EXP_SCRATCH_PAGE][0] = nameLen;
            for (uint8_t i = 0; i < nameLen; i++) buf[EXP_SCRATCH_PAGE][i + 1] = currentFileName[i];
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_REMOVE_SD_FILE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t rmNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                  buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (rmNameLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char rmName[EXP_PATH_ARG_LEN + 1];
            if (rmNameLen > EXP_PATH_ARG_LEN) rmNameLen = EXP_PATH_ARG_LEN;
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2, rmNameLen,
                              rmName);
            char rmFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(rmName, rmFsName, sizeof(rmFsName));
            /* SDRM must only ever delete a file, never a directory --
             * SDRMDIR is the only sanctioned way to remove one. */
            if (IsDirectory(rmFsName)) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            WriteStatus(buf, f_unlink(rmFsName) == FR_OK ? EXP_STATUS_SUCCESS : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_CHANGE_SD_DIR: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t cdNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                  buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (cdNameLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char cdName[EXP_PATH_ARG_LEN + 1];
            if (cdNameLen > EXP_PATH_ARG_LEN) cdNameLen = EXP_PATH_ARG_LEN;
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2, cdNameLen,
                              cdName);
            char cdFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(cdName, cdFsName, sizeof(cdFsName));
            WriteStatus(buf, f_chdir(cdFsName) == FR_OK ? EXP_STATUS_SUCCESS : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_MAKE_SD_DIR: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t mkNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                  buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (mkNameLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char mkName[EXP_PATH_ARG_LEN + 1];
            if (mkNameLen > EXP_PATH_ARG_LEN) mkNameLen = EXP_PATH_ARG_LEN;
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2, mkNameLen,
                              mkName);
            char mkFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(mkName, mkFsName, sizeof(mkFsName));
            WriteStatus(buf, f_mkdir(mkFsName) == FR_OK ? EXP_STATUS_SUCCESS : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_REMOVE_SD_DIR: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t rmdirNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                     buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (rmdirNameLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char rmdirName[EXP_PATH_ARG_LEN + 1];
            if (rmdirNameLen > EXP_PATH_ARG_LEN) rmdirNameLen = EXP_PATH_ARG_LEN;
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2,
                              rmdirNameLen, rmdirName);
            char rmdirFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(rmdirName, rmdirFsName, sizeof(rmdirFsName));
            /* f_unlink() on a directory only succeeds if it's empty
             * (FR_DENIED otherwise) -- same semantics as emFile's
             * FS_RmDir, no extra check needed. f_rmdir is #define'd to
             * f_unlink in ff.h. */
            WriteStatus(buf, f_unlink(rmdirFsName) == FR_OK ? EXP_STATUS_SUCCESS : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_GET_SD_CWD: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            char cwdRaw[64];
            char cwd[64];
            if (f_getcwd(cwdRaw, sizeof(cwdRaw)) != FR_OK) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            NormalizeSdPathFromFs(cwdRaw, cwd, sizeof(cwd));
            ConvertTildeToPlus(cwd);
            uint8_t cwdLen = (uint8_t)strlen(cwd);
            buf[EXP_SCRATCH_PAGE][0] = cwdLen;
            for (uint8_t i = 0; i < cwdLen; i++) buf[EXP_SCRATCH_PAGE][i + 1] = cwd[i];
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_COPY_SD_FILE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint16_t srcLen = (uint16_t)window[0] * 256 + window[1];
            uint16_t destLen = (uint16_t)window[EXP_TWO_NAME_SLOT_LEN] * 256 +
                                window[EXP_TWO_NAME_SLOT_LEN + 1];
            if (srcLen == 0 || destLen == 0 || srcLen > EXP_PATH_ARG_LEN ||
                destLen > EXP_PATH_ARG_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char srcArg[EXP_PATH_ARG_LEN + 1], destArg[EXP_PATH_ARG_LEN + 1];
            for (uint16_t i = 0; i < srcLen; i++) srcArg[i] = (char)window[2 + i];
            srcArg[srcLen] = 0;
            for (uint16_t i = 0; i < destLen; i++)
                destArg[i] = (char)window[EXP_TWO_NAME_SLOT_LEN + 2 + i];
            destArg[destLen] = 0;
            char srcFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(srcArg, srcFsName, sizeof(srcFsName));
            char destFsName[EXP_PATH_ARG_LEN + 16];
            ResolveCopyOrMoveDestination(GetBasename(srcArg), destArg, destFsName,
                                          sizeof(destFsName));
            WriteStatus(buf, CopyFileFatFs(srcFsName, destFsName) ? EXP_STATUS_SUCCESS
                                                                    : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_MOVE_SD_FILE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint16_t srcLen = (uint16_t)window[0] * 256 + window[1];
            uint16_t destLen = (uint16_t)window[EXP_TWO_NAME_SLOT_LEN] * 256 +
                                window[EXP_TWO_NAME_SLOT_LEN + 1];
            if (srcLen == 0 || destLen == 0 || srcLen > EXP_PATH_ARG_LEN ||
                destLen > EXP_PATH_ARG_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char srcArg[EXP_PATH_ARG_LEN + 1], destArg[EXP_PATH_ARG_LEN + 1];
            for (uint16_t i = 0; i < srcLen; i++) srcArg[i] = (char)window[2 + i];
            srcArg[srcLen] = 0;
            for (uint16_t i = 0; i < destLen; i++)
                destArg[i] = (char)window[EXP_TWO_NAME_SLOT_LEN + 2 + i];
            destArg[destLen] = 0;
            char srcFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(srcArg, srcFsName, sizeof(srcFsName));
            char destFsName[EXP_PATH_ARG_LEN + 16];
            ResolveCopyOrMoveDestination(GetBasename(srcArg), destArg, destFsName,
                                          sizeof(destFsName));
            WriteStatus(buf, f_rename(srcFsName, destFsName) == FR_OK ? EXP_STATUS_SUCCESS
                                                                        : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_CHECK_SD_COPY_MOVE_DEST_EXISTS: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint16_t srcLen = (uint16_t)window[0] * 256 + window[1];
            uint16_t destLen = (uint16_t)window[EXP_TWO_NAME_SLOT_LEN] * 256 +
                                window[EXP_TWO_NAME_SLOT_LEN + 1];
            if (srcLen == 0 || destLen == 0 || srcLen > EXP_PATH_ARG_LEN ||
                destLen > EXP_PATH_ARG_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char srcArg[EXP_PATH_ARG_LEN + 1], destArg[EXP_PATH_ARG_LEN + 1];
            for (uint16_t i = 0; i < srcLen; i++) srcArg[i] = (char)window[2 + i];
            srcArg[srcLen] = 0;
            for (uint16_t i = 0; i < destLen; i++)
                destArg[i] = (char)window[EXP_TWO_NAME_SLOT_LEN + 2 + i];
            destArg[destLen] = 0;
            char destFsName[EXP_PATH_ARG_LEN + 16];
            ResolveCopyOrMoveDestination(GetBasename(srcArg), destArg, destFsName,
                                          sizeof(destFsName));
            FILINFO fno;
            WriteStatus(buf, f_stat(destFsName, &fno) == FR_OK ? EXP_STATUS_SUCCESS
                                                                 : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_SD_OPEN_CHANNEL: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint8_t channel = window[0];
            if (channel < 1 || channel > EXP_MAX_SD_CHANNELS) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint16_t nameLen = (uint16_t)window[1] * 256 + window[2];
            if (nameLen == 0 || nameLen > EXP_PATH_ARG_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char name[EXP_PATH_ARG_LEN + 1];
            for (uint16_t i = 0; i < nameLen; i++) name[i] = (char)window[3 + i];
            name[nameLen] = 0;
            char fsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(name, fsName, sizeof(fsName));

            uint8_t idx = channel - 1;
            if (channelOpen[idx]) {
                f_close(&channelFile[idx]);
                channelOpen[idx] = false;
            }
            /* Open for combined read+append -- create if it doesn't
             * exist, never truncate one that does (FA_OPEN_ALWAYS). */
            channelOpen[idx] = f_open(&channelFile[idx], fsName, FA_READ | FA_WRITE | FA_OPEN_ALWAYS) == FR_OK;
            if (!channelOpen[idx]) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            strncpy(channelName[idx], name, EXP_PATH_ARG_LEN);
            channelName[idx][EXP_PATH_ARG_LEN] = 0;
            channelReadPos[idx] = 0;
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_SD_CLOSE_CHANNEL: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint8_t channel = window[0];
            if (channel == 0) {
                for (uint8_t i = 0; i < EXP_MAX_SD_CHANNELS; i++) {
                    if (channelOpen[i]) {
                        f_close(&channelFile[i]);
                        channelOpen[i] = false;
                    }
                    channelName[i][0] = 0;
                    channelReadPos[i] = 0;
                }
                WriteStatus(buf, EXP_STATUS_SUCCESS);
                break;
            }
            if (channel > EXP_MAX_SD_CHANNELS) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint8_t idx = channel - 1;
            if (channelOpen[idx]) {
                f_close(&channelFile[idx]);
                channelOpen[idx] = false;
            }
            channelName[idx][0] = 0;
            channelReadPos[idx] = 0;
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_SD_LIST_CHANNELS: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint16_t count = 0;
            for (uint8_t i = 0; i < EXP_MAX_SD_CHANNELS && count < EXP_DIR_MAX_ENTRIES; i++) {
                if (!channelOpen[i]) continue;
                uint8_t *entry = window + 2 + (uint16_t)count * EXP_DIR_RECORD_SIZE;
                char label[EXP_DIR_NAME_LEN];
                uint8_t pos = 0;
                pos = (uint8_t)(pos + WriteDecimal((uint32_t)(i + 1), (uint8_t *)(label + pos)));
                if (pos < EXP_DIR_NAME_LEN) label[pos++] = ':';
                uint8_t j;
                for (j = 0; channelName[i][j] != 0 && pos < EXP_DIR_NAME_LEN; j++)
                    label[pos++] = channelName[i][j];
                uint8_t labelLen = pos;
                for (j = 0; j < EXP_DIR_NAME_LEN; j++)
                    entry[j] = (j < labelLen) ? (uint8_t)label[j] : ' ';
                for (j = 0; j < EXP_DIR_SIZE_TEXT_LEN; j++) (entry + EXP_DIR_NAME_LEN)[j] = ' ';
                for (j = 0; j < 4; j++) entry[EXP_DIR_NAME_LEN + EXP_DIR_SIZE_TEXT_LEN + j] = 0;
                count++;
            }
            window[0] = (uint8_t)(count >> 8);
            window[1] = (uint8_t)(count & 0xFF);
            {
                uint16_t summaryOffset = (uint16_t)(2 + (uint16_t)count * EXP_DIR_RECORD_SIZE);
                if (summaryOffset + EXP_DIR_SUMMARY_LEN <= 4095) {
                    char summary[16];
                    uint8_t pos = 0;
                    pos = (uint8_t)(pos + WriteDecimal((uint32_t)count, (uint8_t *)(summary + pos)));
                    summary[pos++] = ' ';
                    summary[pos++] = 'O';
                    summary[pos++] = 'P';
                    summary[pos++] = 'E';
                    summary[pos++] = 'N';
                    uint8_t k;
                    for (k = 0; k < EXP_DIR_SUMMARY_LEN; k++)
                        window[summaryOffset + k] = (k < pos) ? (uint8_t)summary[k] : ' ';
                }
            }
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_SD_WRITE_VALUE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint8_t channel = window[0];
            if (channel < 1 || channel > EXP_MAX_SD_CHANNELS || !channelOpen[channel - 1]) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint8_t idx = channel - 1;
            uint8_t tag = window[1];
            uint16_t chunkLen;
            if (tag == 'N') chunkLen = 1 + 8;
            else if (tag == 'S') chunkLen = (uint16_t)(1 + 1 + window[2]);
            else {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            SeekToEnd(&channelFile[idx]);
            UINT written = 0;
            f_write(&channelFile[idx], window + 1, chunkLen, &written);
            if (written != chunkLen) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_SD_READ_VALUE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint8_t channel = window[0];
            if (channel < 1 || channel > EXP_MAX_SD_CHANNELS || !channelOpen[channel - 1]) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint8_t idx = channel - 1;
            f_lseek(&channelFile[idx], channelReadPos[idx]);
            uint8_t tag;
            UINT got = 0;
            f_read(&channelFile[idx], &tag, 1, &got);
            if (got != 1) {
                WriteStatus(buf, EXP_STATUS_EOF);
                break;
            }
            uint16_t payloadLen;
            uint8_t lenByte = 0;
            if (tag == 'N') {
                payloadLen = 8;
            } else if (tag == 'S') {
                f_read(&channelFile[idx], &lenByte, 1, &got);
                if (got != 1) {
                    WriteStatus(buf, EXP_STATUS_EOF);
                    break;
                }
                payloadLen = lenByte;
            } else {
                WriteStatus(buf, EXP_STATUS_ERROR); /* corrupt file */
                break;
            }
            uint8_t payload[255];
            if (payloadLen > 0) {
                f_read(&channelFile[idx], payload, payloadLen, &got);
                if (got != payloadLen) {
                    WriteStatus(buf, EXP_STATUS_EOF);
                    break;
                }
            }
            uint16_t pos = 0;
            window[pos++] = tag;
            if (tag == 'S') window[pos++] = lenByte;
            for (uint16_t i = 0; i < payloadLen; i++) window[pos++] = payload[i];
            channelReadPos[idx] = (uint32_t)f_tell(&channelFile[idx]);
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_SD_SKIP_VALUES: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            uint8_t channel = window[0];
            if (channel < 1 || channel > EXP_MAX_SD_CHANNELS || !channelOpen[channel - 1]) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint8_t idx = channel - 1;
            uint16_t count = (uint16_t)window[1] * 256 + window[2];
            uint32_t pos = channelReadPos[idx];
            bool ok = true;
            for (uint16_t i = 0; i < count; i++) {
                f_lseek(&channelFile[idx], pos);
                uint8_t tag;
                UINT got = 0;
                f_read(&channelFile[idx], &tag, 1, &got);
                if (got != 1) {
                    ok = false;
                    break;
                }
                if (tag == 'N') {
                    pos += 1 + 8;
                } else if (tag == 'S') {
                    uint8_t lenByte = 0;
                    f_read(&channelFile[idx], &lenByte, 1, &got);
                    if (got != 1) {
                        ok = false;
                        break;
                    }
                    pos += (uint32_t)(1 + 1 + lenByte);
                } else {
                    ok = false;
                    break;
                }
            }
            if (!ok) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            channelReadPos[idx] = pos;
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_VALIDATE_SD_NAME: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t nameLen = (uint16_t)buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            uint8_t *name = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 2];
            uint8_t nameCount = 0, extCount = 0, dotSeen = 0, dotOnly = 1, valid = 1;
            uint16_t i;
            for (i = 0; i < nameLen && valid; i++) {
                uint8_t c = name[i];
                if (c >= 'a' && c <= 'z') c = (uint8_t)(c - 'a' + 'A');
                if (c == '/') {
                    nameCount = 0;
                    extCount = 0;
                    dotSeen = 0;
                    dotOnly = 1;
                } else if (c == '.') {
                    if (dotOnly) {
                        /* "." or ".." so far -- allow, don't touch counters */
                    } else if (dotSeen) {
                        valid = 0;
                    } else {
                        dotSeen = 1;
                    }
                } else {
                    dotOnly = 0;
                    if (!dotSeen) {
                        nameCount++;
                        if (nameCount > 8) valid = 0;
                    } else {
                        extCount++;
                        if (extCount > 3) valid = 0;
                    }
                }
                name[i] = c;
            }
            if (nameLen == 0) valid = 0;
            WriteStatus(buf, valid ? EXP_STATUS_SUCCESS : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_GET_SD_DF_TEXT: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint32_t total, free_;
            GetVolumeSpace(&total, &free_);
            char text[32];
            uint8_t pos = 0;
            pos = (uint8_t)(pos + WriteDecimal(free_, (uint8_t *)(text + pos)));
            text[pos++] = 'F';
            text[pos++] = ' ';
            text[pos++] = '/';
            text[pos++] = ' ';
            pos = (uint8_t)(pos + WriteDecimal(total, (uint8_t *)(text + pos)));
            text[pos++] = 'T';
            buf[EXP_SCRATCH_PAGE][0] = pos;
            for (uint8_t i = 0; i < pos; i++) buf[EXP_SCRATCH_PAGE][i + 1] = (uint8_t)text[i];
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_LIST_SD_DIR: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint8_t *window = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            DIR dir;
            FILINFO fno;
            uint16_t count = 0;
            uint32_t totalBytes = 0;
            FRESULT fr = f_findfirst(&dir, &fno, "", "*");
            while (fr == FR_OK && fno.fname[0] != 0 && count < EXP_DIR_MAX_ENTRIES) {
                /* FatFs's own find functions never return "."/".." --
                 * unlike emFile, so this loop never sees them. */
                uint8_t *entry = window + 2 + (uint16_t)count * EXP_DIR_RECORD_SIZE;
                ConvertTildeToPlus(fno.fname);
                uint8_t nameLen = (uint8_t)strlen(fno.fname);
                bool isDir = (fno.fattrib & AM_DIR) != 0;
                if (nameLen > EXP_DIR_NAME_LEN) nameLen = EXP_DIR_NAME_LEN;
                for (uint8_t i = 0; i < EXP_DIR_NAME_LEN; i++)
                    entry[i] = (i < nameLen) ? (uint8_t)fno.fname[i] : ' ';
                if (isDir) {
                    static const char dirText[] = "<DIR>";
                    uint8_t dirTextLen = (uint8_t)(sizeof(dirText) - 1);
                    uint8_t j;
                    for (j = 0; j < EXP_DIR_SIZE_TEXT_LEN; j++) (entry + EXP_DIR_NAME_LEN)[j] = ' ';
                    for (j = 0; j < dirTextLen; j++)
                        (entry + EXP_DIR_NAME_LEN)[EXP_DIR_SIZE_TEXT_LEN - dirTextLen + j] =
                            (uint8_t)dirText[j];
                } else {
                    FormatSizeText((uint32_t)fno.fsize, entry + EXP_DIR_NAME_LEN,
                                    EXP_DIR_SIZE_TEXT_LEN);
                }
                {
                    uint32_t sizeValue = isDir ? 0 : (uint32_t)fno.fsize;
                    entry[EXP_DIR_NAME_LEN + EXP_DIR_SIZE_TEXT_LEN] = (uint8_t)(sizeValue >> 24);
                    entry[EXP_DIR_NAME_LEN + EXP_DIR_SIZE_TEXT_LEN + 1] = (uint8_t)(sizeValue >> 16);
                    entry[EXP_DIR_NAME_LEN + EXP_DIR_SIZE_TEXT_LEN + 2] = (uint8_t)(sizeValue >> 8);
                    entry[EXP_DIR_NAME_LEN + EXP_DIR_SIZE_TEXT_LEN + 3] = (uint8_t)(sizeValue);
                }
                if (!isDir) totalBytes += (uint32_t)fno.fsize;
                count++;
                fr = f_findnext(&dir, &fno);
            }
            f_closedir(&dir);
            window[0] = (uint8_t)(count >> 8);
            window[1] = (uint8_t)(count & 0xFF);
            {
                uint16_t summaryOffset = (uint16_t)(2 + (uint16_t)count * EXP_DIR_RECORD_SIZE);
                if (summaryOffset + EXP_DIR_SUMMARY_LEN <= 4095) {
                    uint32_t total, free_;
                    GetVolumeSpace(&total, &free_);
                    FormatSummaryLine(count, totalBytes, free_, window + summaryOffset,
                                       EXP_DIR_SUMMARY_LEN);
                }
            }
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_CLEAR_STATUS: {
            WriteStatus(buf, EXP_STATUS_READY);
            break;
        }
        case EXP_COMMAND_TEST_DELAY: {
            /* Diagnostic only -- see pc_exp.h's own comment. No SD/I2C
             * work at all, just blocks core1 for N seconds (the ROM-side
             * DOSTUFF keyword's own argument, 0 meaning "default to 1")
             * so the status-poll/watchdog mechanism can be tested in
             * isolation from every other real-hardware variable. */
            uint8_t seconds = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            if (seconds == 0) seconds = 1;
            sleep_ms((uint32_t)seconds * 1000u);
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_CREATE_SD_FILE: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t fileNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                    buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (fileNameLen == 0 || fileNameLen > EXP_PATH_ARG_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char fileName[EXP_PATH_ARG_LEN + 1];
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2, fileNameLen,
                              fileName);
            char fsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(fileName, fsName, sizeof(fsName));
            currentFileOpen = f_open(&currentFile, fsName, FA_CREATE_ALWAYS | FA_WRITE) == FR_OK;
            if (!currentFileOpen) {
                WriteStatus(buf, EXP_STATUS_ERROR);
            } else {
                currentFileStatus = EXP_SD_FILE_STATUS_OPEN_WRITE;
                strncpy(currentFileName, fileName, sizeof(currentFileName) - 1);
                currentFileName[sizeof(currentFileName) - 1] = 0;
                WriteStatus(buf, EXP_STATUS_SUCCESS);
            }
            break;
        }
        case EXP_COMMAND_OPEN_SD_FILE_READ: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t readNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                    buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (readNameLen == 0 || readNameLen > EXP_PATH_ARG_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char readFileName[EXP_PATH_ARG_LEN + 1];
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2, readNameLen,
                              readFileName);
            char readFsName[EXP_PATH_ARG_LEN + 1];
            PrepareFsName(readFileName, readFsName, sizeof(readFsName));
            currentFileOpen = f_open(&currentFile, readFsName, FA_READ) == FR_OK;
            if (!currentFileOpen) {
                WriteStatus(buf, EXP_STATUS_ERROR);
            } else {
                currentFileStatus = EXP_SD_FILE_STATUS_OPEN_READ;
                strncpy(currentFileName, readFileName, sizeof(currentFileName) - 1);
                currentFileName[sizeof(currentFileName) - 1] = 0;
                WriteStatus(buf, EXP_STATUS_SUCCESS);
            }
            break;
        }
        case EXP_COMMAND_GET_SD_FILE_STATUS: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] = currentFileStatus;
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_WRITE_TO_SD_FILE: {
            if (!currentFileOpen || currentFileStatus != EXP_SD_FILE_STATUS_OPEN_WRITE) break;
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t dataLen = (buf[EXP_LENGTH_PORT_PAGE][EXP_LENGTH_PORT_ADDRESS] << 8) +
                                buf[EXP_LENGTH_PORT_PAGE][EXP_LENGTH_PORT_ADDRESS + 1];
            if (dataLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            const uint8_t *src = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            UINT dataWritten = 0;
            f_write(&currentFile, src, dataLen, &dataWritten);
            if (dataWritten == dataLen) {
                WriteStatus(buf, EXP_STATUS_SUCCESS);
                fileEnd += dataLen;
            } else {
                WriteStatus(buf, EXP_STATUS_ERROR);
            }
            break;
        }
        case EXP_COMMAND_READ_FROM_SD_FILE: {
            if (!currentFileOpen || currentFileStatus != EXP_SD_FILE_STATUS_OPEN_READ) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t requestLen = (buf[EXP_LENGTH_PORT_PAGE][EXP_LENGTH_PORT_ADDRESS] << 8) +
                                   buf[EXP_LENGTH_PORT_PAGE][EXP_LENGTH_PORT_ADDRESS + 1];
            if (requestLen == 0 || requestLen > EXP_MAX_TRANSFER_LEN) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            uint8_t *readDest = &buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS];
            UINT bytesRead = 0;
            f_read(&currentFile, readDest, requestLen, &bytesRead);
            buf[EXP_LENGTH_PORT_PAGE][EXP_LENGTH_PORT_ADDRESS] = (uint8_t)(bytesRead >> 8);
            buf[EXP_LENGTH_PORT_PAGE][EXP_LENGTH_PORT_ADDRESS + 1] = (uint8_t)(bytesRead & 255);
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        case EXP_COMMAND_CLOSE_SD_FILE: {
            if (!currentFileOpen || currentFileStatus == EXP_SD_FILE_STATUS_CLOSED) break;
            WriteStatus(buf, EXP_STATUS_BUSY);
            FRESULT result = f_close(&currentFile);
            if (result == FR_OK) {
                currentFileOpen = false;
                currentFileStatus = EXP_SD_FILE_STATUS_CLOSED;
                WriteStatus(buf, EXP_STATUS_SUCCESS);
                LongToBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS, fileEnd);
                fileEnd = 0;
            } else {
                WriteStatus(buf, EXP_STATUS_ERROR);
                LongToBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS, (uint32_t)result);
            }
            break;
        }
        case EXP_COMMAND_FORMAT_SD_CARD: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t volumeNameLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                      buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (volumeNameLen == 0) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char volumeName[EXP_PATH_ARG_LEN + 1];
            if (volumeNameLen > EXP_PATH_ARG_LEN) volumeNameLen = EXP_PATH_ARG_LEN;
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2,
                              volumeNameLen, volumeName);
            static uint8_t mkfsWork[FF_MAX_SS];
            MKFS_PARM opt = {.fmt = FM_ANY, .n_fat = 0, .align = 0, .n_root = 0, .au_size = 0};
            WriteStatus(buf, f_mkfs(volumeName, &opt, mkfsWork, sizeof(mkfsWork)) == FR_OK
                                  ? EXP_STATUS_SUCCESS
                                  : EXP_STATUS_ERROR);
            break;
        }
        case EXP_COMMAND_TEST_COPY_STRING: {
            WriteStatus(buf, EXP_STATUS_BUSY);
            uint16_t dataLen = buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS] * 256 +
                                buf[EXP_BUFFER_START_PAGE][EXP_BUFFER_START_ADDRESS + 1];
            if (dataLen == 0 || dataLen > 254) {
                WriteStatus(buf, EXP_STATUS_ERROR);
                break;
            }
            char testString[255];
            StringFromBuffer(buf, EXP_BUFFER_START_PAGE, EXP_BUFFER_START_ADDRESS + 2, dataLen,
                              testString);
            for (uint16_t i = 0; i < dataLen; i++) buf[4][i + 1] = testString[i];
            buf[4][0] = (uint8_t)dataLen;
            WriteStatus(buf, EXP_STATUS_SUCCESS);
            break;
        }
        default: {
            WriteStatus(buf, EXP_STATUS_NOT_IMPLEMENTED);
            break;
        }
    }
}

/* ============================================================
 * Bus loop -- ported from main()'s for(;;) in main.c, restructured
 * around the GreenPAK's two combined trigger lines (see board_pins.h)
 * instead of separately-sampled CS/RW/OE pins.
 * ============================================================ */

static void InitGpio(void) {
    for (int p = ADDR_PIN_BASE; p < ADDR_PIN_BASE + ADDR_PIN_COUNT; p++) {
        gpio_init(p);
        gpio_set_pulls(p, false, false); /* no internal pull -- even a weak one adds unwanted loading across every bus-facing pin at once. Note this board is NOT unbuffered throughout: the data bus goes through U6 (a TXS0108E level shifter) and the GreenPAK I2C link through U8 (TCA9406DC) -- see board_pins.h/greenpak_i2c.c. The address bus (this loop) and the two trigger lines are the ones the schematic trace found wired directly, with no such component in between. */
    }
    for (int p = DATA_PIN_BASE; p < DATA_PIN_BASE + DATA_PIN_COUNT; p++) {
        gpio_init(p);
        /* Pull-DOWN here, unlike the address/trigger pins above --
         * deliberately different, not an oversight. The data bus is the
         * one path that goes through U6 (a TXS0108E auto-direction-
         * sensing level shifter); those chips are known to misbehave
         * when their low-voltage side floats with no defined level
         * (nothing to sense an edge against), and can inject noise onto
         * the high-voltage side as a result. That would explain the
         * LCD corruption tracking general bus activity everywhere (every
         * memory access shares these lines) rather than anything
         * specific to this expansion window's own reads/writes.
         *
         * CONFIRMED 2026-09-17: removing this pull-down (tested with no
         * pull at all, matching the address/trigger pins) did NOT fix the
         * separate power-on first-read anomaly (see EC_WAIT_NOT_BUSY's/
         * Track 2A's own notes -- that's an output-direction level-shifter
         * lock-in issue, unrelated to this), and made ECVER/DOSTUFF fail
         * consistently instead of intermittently -- direct evidence this
         * pull-down provides real, meaningful noise immunity for general
         * bus reliability. Restored. Do not remove this again without new
         * evidence it's safe to.
         *
         * A firm pull-down is only live while these pins are inputs (the
         * vast majority of the time -- see DriveData()/ReleaseData()
         * below), so it doesn't fight the level shifter during an actual
         * driven transfer. */
        gpio_set_pulls(p, false, true);
    }
    gpio_init(PIN_TRIG_RD);
    gpio_set_pulls(PIN_TRIG_RD, false, false);
    gpio_init(PIN_TRIG_WR);
    gpio_set_pulls(PIN_TRIG_WR, false, false);
    /* Data pins start as inputs (Hi-Z) -- only driven while servicing a
     * read-trigger, see the loop below. Address/trigger pins are always
     * inputs from this chip's side. */
}

/* ============================================================
 * PIO-driven read-trigger path (2026-09-18) -- see read_serve.pio's own
 * header comment for the design. Replaces the software read-trigger
 * branch in monitor_run() below entirely: once running, reads are
 * answered by PIO+DMA in hardware, with no core involved. Write-trigger
 * handling is separately disabled for this phase (see monitor_run()'s own
 * comment) -- this is a deliberate, temporary split to validate the read
 * path in isolation (e.g. via repeated ECVER runs, which only exercise
 * ROM reads through the base ROM's own keyword-table walk) before
 * re-integrating writes.
 *
 * DMA chaining uses OneROM's own documented "continuous" mode (both
 * channels free-running with an effectively-infinite transfer count,
 * paced by the SAME dreq -- the address SM's own RX-FIFO-has-data signal
 * -- rather than an explicit re-trigger). A first attempt used a
 * single-shot "trigger alias" scheme with channel A configured to
 * CHAIN_TO itself, on the mistaken assumption that would make it
 * self-retrigger after each transfer -- confirmed against the actual
 * RP2350 register documentation (hardware/regs/dma.h) that CHAIN_TO set
 * to a channel's own number specifically means "chaining disabled", not
 * self-retrigger. That bug meant channel A fired exactly once, ever, then
 * silently stopped -- starving read_serve's TX FIFO after its first byte
 * and leaving that state machine permanently stalled on its next `out
 * pins, 8`, waiting for an autopull refill that could never arrive again.
 * Confirmed live on real hardware as a hang (ECVER) and an unexplained
 * audible "clicking" from the MCU on a second attempt -- reverted to the
 * last known-good checkpoint before diagnosing this from the datasheet,
 * then reapplied here with the corrected continuous-mode design. */

static uint dma_addr_relay, dma_data_fetch;
static uint sm_addr_capture, sm_read_serve;

static void SetupReadServePio(void) {
    /* Data pins need to be owned by PIO0 to actually be driven by it;
     * address/trigger pins don't -- PIO's IN/WAIT/JMP-on-pin instructions
     * read the GPIO input synchronizer directly regardless of which
     * peripheral has function-select ownership, so InitGpio()'s existing
     * plain-GPIO configuration for those is left alone. */
    for (int p = DATA_PIN_BASE; p < DATA_PIN_BASE + DATA_PIN_COUNT; p++) {
        pio_gpio_init(pio0, p);
    }
    pio_sm_set_consecutive_pindirs(pio0, 0, DATA_PIN_BASE, DATA_PIN_COUNT, false); /* start as inputs */

    sm_addr_capture = pio_claim_unused_sm(pio0, true);
    sm_read_serve = pio_claim_unused_sm(pio0, true);
    uint offset_addr = pio_add_program(pio0, &addr_capture_program);
    uint offset_read = pio_add_program(pio0, &read_serve_program);

    /* addr_capture: on each rising edge of PIN_TRIG_RD, shifts (fixed
     * buffer-base prefix) then (live 13-bit address bus) into a 32-bit
     * ISR, autopushed to RX FIFO -- see buffer[]'s own 8192-byte-alignment
     * comment for why this produces a correct, ready-to-use absolute
     * address, and read_serve.pio's own header comment for why capture is
     * gated on the trigger (edge-gated redesign, 2026-09-18). */
    pio_sm_config c_addr = addr_capture_program_get_default_config(offset_addr);
    sm_config_set_in_pins(&c_addr, ADDR_PIN_BASE);
    sm_config_set_jmp_pin(&c_addr, PIN_TRIG_RD);   /* gates capture on the
                                                       read trigger; see
                                                       read_serve.pio's
                                                       header */
    sm_config_set_in_shift(&c_addr, false /* shift left */, true /* autopush */, 32);
    /* Full speed, undivided (~150MHz) clock -- an earlier /125 divider
     * caused this SM to almost always sample the address bus during its
     * idle/rest state instead of the brief live-address window a real
     * LH5801 read cycle presents (every live address bit tested came back
     * 0 on real hardware). Now that capture is also edge-gated on
     * PIN_TRIG_RD (see read_serve.pio's header and sm_config_set_jmp_pin
     * above), full speed additionally matters so the wait_high/wait_low
     * poll loop notices the trigger's rising and falling edges promptly
     * enough to finish capturing well inside the trigger's own asserted
     * window, rather than for the "flood of DMA transfers" reason this
     * divider was originally about -- that concern no longer applies at
     * all now that a transfer only ever happens once per real access. */
    sm_config_set_clkdiv(&c_addr, 1.0f);
    pio_sm_init(pio0, sm_addr_capture, offset_addr, &c_addr);

    /* Preload X with the fixed prefix (buffer's own base address's high
     * 19 bits) -- matches OneROM's own setup-time PULL_BLOCK/MOV X,OSR
     * sequence, done once before the SM starts running. */
    uint32_t buffer_base = (uint32_t)(uintptr_t)buffer;
    uint32_t prefix = buffer_base >> ADDR_PIN_COUNT;
    pio_sm_put_blocking(pio0, sm_addr_capture, prefix);
    pio_sm_exec_wait_blocking(pio0, sm_addr_capture, pio_encode_pull(false, true));
    pio_sm_exec_wait_blocking(pio0, sm_addr_capture, pio_encode_mov(pio_x, pio_osr));

    /* read_serve: drives the data pins from whatever byte the DMA chain
     * below has staged in this SM's TX FIFO, only while PIN_TRIG_RD is
     * asserted. */
    pio_sm_config c_read = read_serve_program_get_default_config(offset_read);
    sm_config_set_out_pins(&c_read, DATA_PIN_BASE, DATA_PIN_COUNT);
    /* shift RIGHT (2026-09-18, corrected from an initial wrong guess of
     * shift-left): an 8-bit-sized DMA write into this SM's 32-bit TX FIFO
     * register places the byte in the low byte lane (bits 7:0). Shift-right
     * is also the SDK's own default convention (pio_get_default_sm_config())
     * for exactly this reason -- OUT consumes the low bits first, matching
     * where the DMA-written byte actually landed. Shift-left would instead
     * read the upper, never-written (zero) bits -- confirmed live on real
     * hardware: every PEEK returned 0 with shift-left, a clean, non-random
     * failure consistent with this exact mistake (not a hang or garbage,
     * since the state machine was otherwise running correctly after fixing
     * the earlier chain_to bug). */
    sm_config_set_out_shift(&c_read, true, true /* autopull */, 8);
    pio_sm_init(pio0, sm_read_serve, offset_read, &c_read);

    /* DMA chain -- redesigned (2026-09-18) around RP2350's TRIGGER_SELF
     * transfer-count mode plus channel B's own triggering address alias,
     * replacing the earlier "continuous mode, dreq-paced" design after
     * two rounds of real-hardware fixes (a fixed TXOVER bug, then
     * channel A still never draining addr_capture's RX FIFO -- confirmed
     * via the same USB-serial FDEBUG/PC/FIFO-level diagnostic showing
     * addr_capture permanently stuck full and its PC frozen, meaning
     * channel A's dreq-paced "continuous" transfer never actually
     * resumed after its first few words despite reporting BUSY the whole
     * time -- root cause not conclusively identified, but the design
     * itself wasn't RP2350's documented idiom for this exact pattern).
     *
     * RP2350's own transfer_count register has a MODE field (top 4 bits,
     * confirmed via hardware/regs/dma.h -- NOT present on RP2040, where
     * the whole register is a plain 32-bit count): MODE 0x1
     * (TRIGGER_SELF) makes a single-element transfer automatically
     * re-trigger itself once it completes -- the datasheet's own words,
     * "useful for e.g. an endless ring-buffer DMA". This is also what
     * OneROM's own original design (this whole approach's namesake)
     * actually does, which this project's earlier "continuous mode"
     * redesign (adopted after the first chain_to incident) deviated from
     * unnecessarily -- chain_to-to-self only breaks *chain_to-driven*
     * self-retriggering (MODE 0x0), not TRIGGER_SELF's own, separate
     * built-in mechanism (MODE 0x1), so there was never a real need to
     * abandon per-element triggering in the first place.
     *   - Channel A: ONE element per transfer (COUNT=1, MODE=TRIGGER_SELF),
     *     paced by addr_capture's RX dreq -- each time a new address word
     *     arrives, reads it and writes it to channel B's *triggering*
     *     al3_read_addr_trig alias (setting the address AND immediately
     *     starting channel B's own transfer as one hardware-native
     *     action), then automatically re-arms itself for the next word.
     *   - Channel B: ONE element per transfer (COUNT=1, MODE=NORMAL,
     *     chain_to left at its default/self, i.e. no auto-chaining --
     *     deliberate, since it should only ever run when channel A's
     *     al3 write above triggers it, never on its own), no dreq at all
     *     needed (unpaced -- once triggered, it just runs immediately):
     *     reads one byte from whatever address channel A most recently
     *     set and hands it to read_serve's TX FIFO. Configured but NOT
     *     triggered at setup time (trigger=false) -- its first real
     *     transfer comes from channel A's first al3 write, not from
     *     this initial configuration call.
     *
     * Bench-tested 2026-09-18 with the board powered over USB only (no
     * PC-1500 attached, so no real PIN_TRIG_RD pulses ever occur), against
     * the addr_capture design at the time (unconditional/continuous, since
     * replaced by the edge-gated redesign -- see read_serve.pio's header):
     * the 1s printf diagnostic below showed channel B's transfer_count
     * alternating 0/1 across an 8-second capture -- direct proof this
     * TRIGGER_SELF/al3-trigger DMA chain itself keeps being re-triggered
     * and re-armed repeatedly, not just once (the specific failure
     * signature the OLDER continuous-mode DMA design never produced --
     * that one fired channel A exactly once, ever, then froze). This DMA
     * chain design is unchanged by the edge-gating fix and remains valid.
     *
     * What's no longer expected, now that addr_capture only captures once
     * per real trigger edge instead of continuously: with no PC-1500
     * attached (nothing ever asserts PIN_TRIG_RD), addr_capture's RX FIFO
     * and read_serve's TX FIFO should now sit EMPTY (addr_rxlvl/
     * serve_txlvl reading 0), not permanently full with RXSTALL/TXOVER
     * set as they did under the old unconditional-capture design -- a
     * future bench test still seeing them full/stalled would indicate a
     * real regression, not an artifact to ignore. */
    dma_addr_relay = dma_claim_unused_channel(true);
    dma_data_fetch = dma_claim_unused_channel(true);

    uint addr_capture_dreq = pio_get_dreq(pio0, sm_addr_capture, false /* rx */);

    dma_channel_config ca = dma_channel_get_default_config(dma_addr_relay);
    channel_config_set_transfer_data_size(&ca, DMA_SIZE_32);
    channel_config_set_read_increment(&ca, false);
    channel_config_set_write_increment(&ca, false);
    channel_config_set_dreq(&ca, addr_capture_dreq);
    dma_channel_configure(
        dma_addr_relay,
        &ca,
        &dma_channel_hw_addr(dma_data_fetch)->al3_read_addr_trig, /* TRIGGERING alias -- this write both
                                                                       sets channel B's read address AND
                                                                       starts its transfer */
        &pio0->rxf[sm_addr_capture],
        (1u << 28) | 1u, /* MODE=0x1 (TRIGGER_SELF, bits 31:28), COUNT=1 (bits 27:0) */
        true
    );

    dma_channel_config cb = dma_channel_get_default_config(dma_data_fetch);
    channel_config_set_transfer_data_size(&cb, DMA_SIZE_8);
    channel_config_set_read_increment(&cb, false);
    channel_config_set_write_increment(&cb, false);
    /* No dreq set -- default unpaced (DREQ_FORCE), correct here since
       channel B should run immediately, at full speed, the instant
       channel A's al3 write above triggers it, not wait on anything
       further. */
    dma_channel_configure(
        dma_data_fetch,
        &cb,
        &pio0->txf[sm_read_serve],
        buffer, /* placeholder initial address -- channel A's first al3 write overwrites this
                    before it's ever meaningfully read */
        1u, /* MODE=0x0 (NORMAL), COUNT=1 -- one element per external trigger from channel A */
        false /* do NOT trigger here -- channel A's first al3 write is what starts channel B */
    );

    pio_sm_set_enabled(pio0, sm_addr_capture, true);
    pio_sm_set_enabled(pio0, sm_read_serve, true);
}

static inline uint16_t ReadAddress(uint32_t gpio_in) {
    return (uint16_t)((gpio_in >> ADDR_PIN_BASE) & ADDR_PIN_MASK);
}

static inline uint8_t ReadDataIn(uint32_t gpio_in) {
    return (uint8_t)((gpio_in >> DATA_PIN_BASE) & ((1u << DATA_PIN_COUNT) - 1u));
}

static inline void DriveData(uint8_t value) {
    uint32_t mask = ((1u << DATA_PIN_COUNT) - 1u) << DATA_PIN_BASE;
    uint32_t bits = ((uint32_t)value << DATA_PIN_BASE) & mask;
    /* Value written BEFORE enabling output -- reversed from an earlier
     * version of this function that set gpio_oe_set first. That ordering
     * briefly drove the bus with gpio_out's STALE previous value (from
     * whatever byte was last put on the bus) for the few cycles between
     * the two register writes, before the correct value landed -- a real
     * race if the LH5801 samples close to the trigger edge, since the
     * trigger itself is already derived from the LH5801's own read-cycle
     * timing. Plausible root cause (2026-09-17) for intermittent wrong
     * bytes served on ROM reads: e.g. ECVER's own KEYWORD_TABLE
     * character-matching walk on the LH5801 side occasionally seeing a
     * stale byte and concluding no keyword matched. Writing the value
     * first means the pins carry the correct byte from the very first
     * instant they're switched to output -- no stale-data window at all. */
    sio_hw->gpio_out = (sio_hw->gpio_out & ~mask) | bits;
    sio_hw->gpio_oe_set = mask; /* NOW switch data pins to output */
}

static inline void ReleaseData(void) {
    sio_hw->gpio_oe_clr = ((1u << DATA_PIN_COUNT) - 1u) << DATA_PIN_BASE;
}

void flash_led(uint32_t duration_ms) {
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 0);
    sleep_ms(duration_ms);
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);
}

void monitor_run(void) {
    InitGpio();

    /* Level-shifter warm-up transaction (2026-09-17). U6 (TXS0108E) has its
     * OE pin tied directly to the 3.3V rail (VCCA), not sequenced by this
     * firmware -- confirmed with the board's owner that OE comes up at the
     * same instant as VCCA itself, before the chip's internal
     * direction-sensing state has necessarily settled (the TXS0108E
     * datasheet documents OE needing to come up after both rails are
     * stable; this board doesn't do that). Confirmed live on real hardware:
     * the very first output-drive transaction after power-on reads back
     * wrong (0xFF) on the LH5801 side every single time, and every
     * subsequent one is correct, regardless of which address is involved --
     * ruling out an address- or data-value-specific cause, and ruling out
     * (by direct A/B test) the separate data-pin pull-down below as the
     * cause. Since firmware has no control over OE's own timing, the
     * cheapest available workaround is to deliberately burn that first bad
     * transaction here, on a value nothing depends on, before the real bus
     * loop below could ever let the LH5801 observe it. sleep_us(10) gives
     * the shifter a real, sustained transition to lock its direction
     * sensing onto, rather than a drive-then-immediately-release pulse too
     * short to register. NOT YET VERIFIED on real hardware -- the unit this
     * was characterized on died (unrelated to this change) before this fix
     * could be tested; verify with the same POKE/PEEK sequence used to
     * characterize the anomaly before trusting this. */
    DriveData(0x00);
    sleep_us(10);
    ReleaseData();

    /* PIO-driven read path takes over data-pin ownership from here --
     * must come after the warm-up transaction above (which needs the data
     * pins still plain SIO GPIO, matching DriveData()/ReleaseData()'s own
     * raw sio_hw register access) and before the loop below, which no
     * longer handles reads in software at all.
     *
     * TEMPORARY DIAGNOSTIC (2026-09-18): LED off immediately before this
     * call, back on immediately after -- main.c already turns it on once
     * cyw43_arch_init() succeeds, so by this point it should already be
     * lit. If it goes dark here and never comes back on, SetupReadServePio()
     * is hanging internally (e.g. stuck in one of its blocking PIO exec
     * calls) and never reaching pio_sm_set_enabled() -- which would also
     * fully explain every PEEK reading 0: the data pins would simply be
     * left in their InitGpio()-configured default (plain SIO input, pulled
     * down), forever, regardless of any real trigger or address, since
     * neither state machine would ever actually start running. Remove
     * once the read path is confirmed working. */
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 0);
    SetupReadServePio();
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);

    /* cyw43_arch_init() is NOT called here -- moved to main.c/core0, see
     * its own comment: calling it from core1 kept the LED dark entirely
     * (plausibly failing or hanging), instead of just failing to react to
     * bus triggers. */

    /* LED on at the top of the loop -- proves this loop is actually
     * running (main.c already turns it on once cyw43_arch_init()
     * succeeds, but this is the loop's own confirmation that it got
     * here). Off for 100ms/200ms below on read/write-trigger, back on
     * after. */
    // cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);

    /* buffer[page][laddress] addressing matches the original's
     * 16-page-wide (or 32-page for the ROM region) local layout: the
     * 13-bit flat address here splits the same way -- low 8 bits are
     * `laddress`, remaining bits are `page`, exactly like
     * Pin_Address_Low_PS/Status_Page_Status did on the PSoC5 side. */
    /* TEMPORARY DIAGNOSTIC (2026-09-18), round 3: rounds 1-2 used the
     * onboard LED (blink-rate/on-off encoding) to narrow down a stall in
     * the addr_capture -> DMA channel A -> DMA channel B -> read_serve
     * chain, since PEEK-based testing showed a couple of correct-but-stale
     * bytes served after boot, then permanent zeros. Switched to real
     * printf() diagnostics over USB CDC (see CMakeLists.txt's own comment
     * on why UART couldn't be used instead -- its pins double as address
     * bus lines) for direct, detailed visibility instead of interpreting
     * LED patterns: every ~1s, print both DMA channels' CTRL_TRIG (BUSY/
     * error bits) and live transfer_count, plus both PIO SMs' own FIFO
     * fill levels and program counters -- enough to see exactly where in
     * the chain things stop moving, in one shot, without needing repeated
     * flash/test/report round-trips. Remove once the stall is found and
     * fixed. */
    uint32_t last_dma_diag_us = time_us_32();

    for (;;) {
        /* Command watchdog -- see g_command_start_us's own comment.
         * Cheap enough (one buffer read, one subtraction/compare, only
         * ever both true while a command is actually in flight) to check
         * unconditionally every iteration without touching the read/
         * write-trigger timing budget. */
        if (buffer[EXP_INSTRUCTION_PAGE][EXP_INSTRUCTION_ADDRESS] == EXP_STATUS_BUSY &&
            time_us_32() - g_command_start_us > COMMAND_TIMEOUT_US) {
            buffer[EXP_INSTRUCTION_PAGE][EXP_INSTRUCTION_ADDRESS] = EXP_STATUS_ERROR;
        }

        if (time_us_32() - last_dma_diag_us > 1000000u) {
            dma_channel_hw_t *ca = dma_channel_hw_addr(dma_addr_relay);
            dma_channel_hw_t *cb = dma_channel_hw_addr(dma_data_fetch);
            printf("chA ctrl=%08x cnt=%08x raddr=%08x waddr=%08x | "
                   "chB ctrl=%08x cnt=%08x raddr=%08x waddr=%08x | "
                   "addr_pc=%u addr_rxlvl=%u | serve_pc=%u serve_txlvl=%u | "
                   "pio_ctrl=%08x pio_fdebug=%08x\n",
                   (unsigned)ca->ctrl_trig, (unsigned)ca->transfer_count,
                   (unsigned)ca->read_addr, (unsigned)ca->write_addr,
                   (unsigned)cb->ctrl_trig, (unsigned)cb->transfer_count,
                   (unsigned)cb->read_addr, (unsigned)cb->write_addr,
                   (unsigned)pio_sm_get_pc(pio0, sm_addr_capture),
                   (unsigned)pio_sm_get_rx_fifo_level(pio0, sm_addr_capture),
                   (unsigned)pio_sm_get_pc(pio0, sm_read_serve),
                   (unsigned)pio_sm_get_tx_fifo_level(pio0, sm_read_serve),
                   (unsigned)pio0->ctrl, (unsigned)pio0->fdebug);
            pio0->fdebug = pio0->fdebug; /* write-1-to-clear the sticky
                                             stall flags after each read,
                                             so next second's printout
                                             shows only NEW stall events,
                                             not the same one forever. */
            last_dma_diag_us = time_us_32();
        }

        /* Read-trigger handling REMOVED from software entirely (2026-09-18)
         * -- SetupReadServePio() above now owns the data pins and answers
         * every read trigger in PIO+DMA hardware, with no core involved.
         * See read_serve.pio's own header comment.
         *
         * Write-trigger handling temporarily DISABLED (2026-09-18), not
         * yet ported to PIO -- deliberate, temporary split to validate
         * the read path in isolation first (per explicit direction: focus
         * on read-serving now, re-integrate writes once that's confirmed
         * solid on real hardware). This means POKE, and every expansion
         * command that depends on writing EXP_INSTRUCTION_ABS to dispatch
         * (DOSTUFF, SDLS, all SD commands), do not work in this build --
         * only pure-read paths do, e.g. ECVER via the base ROM's own
         * keyword-table walk, or PEEK anywhere in the 8K window. The
         * commented-out block below is the original software write path,
         * kept verbatim (not deleted) so re-enabling it later is a
         * revert, not a rewrite, once it's similarly ported to PIO+DMA.
         *
        uint32_t gpio_in = sio_hw->gpio_in;
        bool writeTrigger = (gpio_in & (1u << PIN_TRIG_WR)) != 0;
        if (writeTrigger) {
            gpio_in = sio_hw->gpio_in;
            uint16_t addr = ReadAddress(gpio_in);
            uint8_t page = (uint8_t)(addr >> 8);
            uint8_t laddress = (uint8_t)(addr & 0xFF);
            uint8_t data = ReadDataIn(gpio_in);

            if (page == EXP_INSTRUCTION_PAGE && laddress == EXP_INSTRUCTION_ADDRESS) {
                while (sio_hw->gpio_in & (1u << PIN_TRIG_WR)) {
                }
                buffer[EXP_INSTRUCTION_PAGE][EXP_INSTRUCTION_ADDRESS] = EXP_STATUS_BUSY;
                g_command_start_us = time_us_32();
                multicore_fifo_push_blocking(data);
            } else {
                buffer[page][laddress] = data;
                while (sio_hw->gpio_in & (1u << PIN_TRIG_WR)) {
                }
            }
        }
        */
    }
}

/* Runs forever on core1 -- see monitor.h's own comment. */
void monitor_command_worker(void) {
    for (;;) {
        uint32_t cmd = multicore_fifo_pop_blocking();
        DoCommand((uint8_t)cmd, buffer);
    }
}
