/* Copyright (c) 2026 Paul Chambre. Licensed under the Apache License,
 * Version 2.0 -- see LICENSE.
 */
/* time_zone.h -- MCONF TZ (2026-10-08): IANA zone names, the POSIX TZ rule
 * each follows now (tz_table.c, generated by tools/gen_tz_table.py), and
 * local time from UTC under such a rule -- for the clock set from SNTP
 * (time_sync.h). The BLE host app sends its own local time, so this is
 * only needed with Wi-Fi.
 *
 * Plain C with no SDK calls: the emulator's expansion mock builds it too.
 * It evaluates the rule itself rather than through setenv("TZ")/tzset(),
 * which would mean newlib's heap on the MCU and, on a Windows host, a CRT
 * that can't read the DST part. */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The longest name or rule MCONF TZ keeps (the longest IANA name,
 * America/Argentina/ComodRivadavia, is 32). */
#define TZ_NAME_MAX 47

typedef struct {
    const char *name;
    uint16_t rule;    /* tz_table_rule()'s index */
    uint16_t shifts;  /* kTzShifts index of the zone's scheduled changes... */
    uint16_t nshifts; /* ...and how many (0: the rule covers 2026 on) */
} tz_entry_t;

/* A zone's offset (seconds east of UTC) from `at` (Unix seconds) on. A
 * zone's first is its offset at 2026-01-01; its rule takes over at its
 * last. */
typedef struct {
    int64_t at;
    int32_t offset;
} tz_shift_t;

/* tz_table.c: sorted by the name in upper case with '_' as ' ' */
extern const tz_entry_t kTzTable[];
extern const tz_shift_t kTzShifts[];
extern const unsigned kTzTableCount;
const char *tz_table_rule(unsigned index);

/* A POSIX TZ rule, parsed: offsets in seconds east of UTC (local = UTC +
 * offset -- the opposite of POSIX's own sign). */
typedef struct {
    int32_t std_offset, dst_offset;
    bool has_dst;
    struct tz_change {
        uint8_t kind; /* 'J' Jn, 'D' n, 'M' Mm.w.d */
        uint16_t day; /* Jn/n's n, or Mm.w.d's d */
        uint8_t month, week;
        int32_t time; /* seconds after local midnight; may be negative or past 24h */
    } start, end;
} tz_rule_t;

/* A zone: its rule, and its scheduled changes (none for a typed rule). */
typedef struct {
    tz_rule_t rule;
    const tz_shift_t *shifts;
    uint16_t nshifts;
} tz_zone_t;

/* The zone `name` (`len` characters, any case, '_' or ' '): an IANA name
 * in the table, or a POSIX rule itself, into *zone. The name as it should
 * be stored -- the table's spelling, or the rule as typed -- goes to
 * `canonical` (TZ_NAME_MAX + 1 bytes). False for neither. */
bool tz_find(const char *name, uint8_t len, char *canonical, tz_zone_t *zone);

/* False for a malformed rule. */
bool tz_parse(const char *posix, tz_rule_t *out);

/* Seconds east of UTC in effect at `utc` (Unix seconds). */
int32_t tz_offset_at(const tz_zone_t *zone, int64_t utc);

/* The PC-1500 clock's 5 bytes (pc_exp.h EXP_COMMAND_TIME_GET) for
 * `local` (Unix seconds, already in local time): month<<4 | day of week
 * (0 Sunday), then BCD day, hour, minute, second. */
void tz_clock_bytes(int64_t local, uint8_t out[5]);

#ifdef __cplusplus
}
#endif
