#!/usr/bin/env python3
"""Converts a Hershey .jhf font (here rowmans.jhf, Roman Simplex) into the C
table ../hershey_simplex.c used by the CE-150 plotter emulation.

    python jhf_to_c.py rowmans.jhf ../hershey_simplex.c

.jhf format (one glyph per line, in ASCII order from 0x20): columns 0-4 the
glyph number, 5-7 the number of coordinate pairs that follow (including the
first, which is the glyph's left and right extent), then the pairs: each
coordinate is a character, its value ord(c) - ord('R'); the pair " R" lifts
the pen. x grows to the right, y DOWN (the cap height is about -12..+9, the
baseline +9).

The font data's licence (fonts/NOTICE-hershey.txt) requires its
acknowledgement to travel with it; the generated file carries it. This is a
conversion into a C table, not the U.S. NTIS format.
"""
import sys

PEN_UP = -128
FIRST = 0x20
COUNT = 96  # 0x20-0x7E, then a degree sign (Hershey 718) at 0x7F


def parse(path):
    glyphs = []
    with open(path, encoding="ascii") as f:
        for raw in f:
            line = raw.rstrip("\r\n")
            if not line.strip():
                continue
            n = int(line[5:8])
            body = line[8:]
            if len(body) != 2 * n:
                raise SystemExit(f"glyph {line[:5].strip()}: {n} pairs expected, {len(body) // 2} found")
            pairs = [(body[i], body[i + 1]) for i in range(0, len(body), 2)]
            left, right = (ord(c) - ord("R") for c in pairs[0])
            points = []
            for a, b in pairs[1:]:
                if a == " " and b == "R":
                    points.append((PEN_UP, PEN_UP))
                else:
                    points.append((ord(a) - ord("R"), ord(b) - ord("R")))
            glyphs.append((left, right, points))
    if len(glyphs) != COUNT:
        raise SystemExit(f"{len(glyphs)} glyphs, {COUNT} expected (0x20-0x7F)")
    return glyphs


def main():
    src, dst = sys.argv[1], sys.argv[2]
    glyphs = parse(src)
    out = []
    out.append("/* hershey_simplex.c -- GENERATED by fonts/jhf_to_c.py from fonts/rowmans.jhf;")
    out.append(" * don't edit by hand. See hershey_simplex.h.")
    out.append(" *")
    out.append(" * The Hershey Fonts were originally created by Dr. A. V. Hershey while")
    out.append(" * working at the U. S. National Bureau of Standards.")
    out.append(" * The format of the Font data in this distribution was originally created")
    out.append(" * by James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica,")
    out.append(" * MA 01821 (mit-eddie!ci-dandelion!hurt).")
    out.append(" * (Licence and source: fonts/NOTICE-hershey.txt.) */")
    out.append('#include "hershey_simplex.h"')
    out.append("")
    data, index = [], []
    for left, right, points in glyphs:
        index.append((left, right, len(points), len(data) // 2))
        for x, y in points:
            data.extend([x, y])
    out.append("const int8_t kHersheyPoints[] = {")
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(str(v) for v in data[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append("const hershey_glyph_t kHersheyGlyphs[HERSHEY_COUNT] = {")
    for code, (left, right, count, offset) in enumerate(index, FIRST):
        shown = {0x7F: "degree", 0x2F: "slash"}.get(code) or (chr(code) if chr(code) not in "\\'" else "\\" + chr(code))
        out.append(f"    {{{left}, {right}, {count}, {offset}}}, /* '{shown}' */")
    out.append("};")
    with open(dst, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"{dst}: {COUNT} glyphs, {len(data) // 2} points, {len(data) + COUNT * 5} bytes")


if __name__ == "__main__":
    main()
