#!/usr/bin/env python3
# Copyright (c) 2026 Paul Chambre. Licensed under the Apache License,
# Version 2.0 -- see LICENSE.
"""gp6_to_header.py -- converts a GreenPAK Designer ".gp6" project's
compiled <nvmData> blob into a generated C header (a 256-byte array),
for embedding into the GreenPAK NVM programmer firmware
(RP2350/RP2350B's `greenpak_provision` target).

One-off dev-machine tool, NOT run by the firmware at build/runtime --
the firmware only ever includes the generated header. Re-run this
manually whenever the source .gp6 changes.

Usage:
    python3 gp6_to_header.py <path-to-gp6> <array-name> <output-header>

Example:
    python3 gp6_to_header.py \\
        "C:\\Users\\paulc\\Documents\\PC1500ExpansionBoard\\GreenPak\\GP1-SRAM.gp6" \\
        GP1_NVM_IMAGE \\
        gp1_nvm_image.h
"""
import re
import sys
from datetime import datetime, timezone

NVM_BYTE_COUNT = 256  # 2048 bits = 16 pages x 16 bytes


def extract_nvm_bytes(gp6_path):
    with open(gp6_path, encoding="utf-8", errors="replace") as f:
        text = f.read()

    # NOTE: "registerLenght" is a real misspelling present in the actual
    # GreenPAK Designer output -- match it exactly, don't "fix" it here.
    m = re.search(
        r'<nvmData\s+registerLenght="(\d+)">([^<]*)</nvmData>', text
    )
    if not m:
        sys.exit(f"error: no <nvmData> element found in {gp6_path}")

    bit_length = int(m.group(1))
    tokens = m.group(2).split()
    byte_count = bit_length // 8

    if len(tokens) != byte_count:
        sys.exit(
            f"error: {gp6_path}'s <nvmData> declares {bit_length} bits "
            f"({byte_count} bytes) but contains {len(tokens)} tokens -- "
            f"refusing to emit a possibly-truncated/misparsed image"
        )
    if byte_count != NVM_BYTE_COUNT:
        sys.exit(
            f"error: expected {NVM_BYTE_COUNT}-byte NVM image, "
            f"{gp6_path} declares {byte_count} bytes -- unexpected chip/"
            f"format, refusing to guess"
        )

    try:
        return [int(tok, 16) for tok in tokens]
    except ValueError as e:
        sys.exit(f"error: non-hex token in <nvmData>: {e}")


def extract_last_change(gp6_path, text=None):
    if text is None:
        with open(gp6_path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    m = re.search(r'<GPDProject[^>]*\blastChange="([^"]*)"', text)
    return m.group(1) if m else "(unknown)"


def emit_header(gp6_path, array_name, byte_values, last_change, out_path):
    lines = []
    lines.append("/* Copyright (c) 2026 Paul Chambre. Licensed under the Apache License,")
    lines.append(" * Version 2.0 -- see LICENSE.")
    lines.append(" */")
    lines.append(f"/* GENERATED by tools/gp6_to_header.py -- do not hand-edit.")
    lines.append(f" * Source:      {gp6_path}")
    lines.append(f" * lastChange:  {last_change}")
    lines.append(f" * Generated:   {datetime.now(timezone.utc).isoformat()}")
    lines.append(f" * Re-run the script if the source .gp6 changes -- this file")
    lines.append(f" * will silently go stale otherwise. */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define {array_name}_AVAILABLE 1")
    lines.append(f"#define {array_name}_LEN {len(byte_values)}")
    lines.append("")
    lines.append(f"static const uint8_t {array_name}[{array_name}_LEN] = {{")
    for i in range(0, len(byte_values), 12):
        row = byte_values[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in row) + ",")
    lines.append("};")
    lines.append("")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"wrote {out_path}: {len(byte_values)} bytes from {gp6_path} "
          f"(lastChange={last_change})")


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    gp6_path, array_name, out_path = sys.argv[1:4]

    with open(gp6_path, encoding="utf-8", errors="replace") as f:
        text = f.read()

    byte_values = extract_nvm_bytes(gp6_path)
    last_change = extract_last_change(gp6_path, text)
    emit_header(gp6_path, array_name, byte_values, last_change, out_path)


if __name__ == "__main__":
    main()
